reports:
  exclude_contracts:
    - SafeMath
dependencies:
  - smartcontractkit/chainlink@1.11.0
  - OpenZeppelin/openzeppelin-contracts@4.8.1
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink@1.11.0"
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.8.1"
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
networks:
  default: development
  development:
    gas_lane: "0x79d3d8832d904592c0bf9818b621522c988bb8b0c05cdc3b15aea1b6e8db0c15"
    callback_gas_limit: "500000"
    interval: "85500" #23 hours and 45minutes in seconds (15min for caclulating winner)
    lotteryFee: 100000000000000000
  goerli:
    nft_collection: "0xd16450A02531e852F024f0b9cAC91476D7400cfE"
    eth_usd_price_feed: "0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e"
    vrf_coordinator: "0x2Ca8E0C643bDe4C2E08ab1fA0da3401AdAD7734D"
    gas_lane: "0x79d3d8832d904592c0bf9818b621522c988bb8b0c05cdc3b15aea1b6e8db0c15"
    subscription_id: "9792"
    callback_gas_limit: "500000"
    interval: "85500"
    lotteryFee: 100000000000000000
  mainnet-fork:
    eth_usd_price_feed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
    vrf_coordinator: "0x2Ca8E0C643bDe4C2E08ab1fA0da3401AdAD7734D"
